export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL";

export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST";
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS";
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL";
export const BLOG_DETAILS_RESET = "BLOG_DETAILS_RESET";

export const BLOG_CREATE_COMMENT_FAIL = "BLOG_CREATE_COMMENT_FAIL";
export const BLOG_CREATE_COMMENT_REQUEST = "BLOG_CREATE_COMMENT_REQUEST";
export const BLOG_CREATE_COMMENT_SUCCESS = "BLOG_CREATE_COMMENT_SUCCESS";
export const BLOG_CREATE_COMMENT_RESET = "BLOG_CREATE_COMMENT_RESET";
